### ISSUE TITLE
exec: "gcc": executable file not found in $PATH

### ISSUE THREAD

**Issue by jmreicha** [gliderlabs/logspout#223]
I am building a custom image and getting the following gcc error:

```
docker build -t logspout-test .                                                                                                                 
Sending build context to Docker daemon 4.096 kB
Step 1 : FROM gliderlabs/logspout:master
# Executing 3 build triggers...
Step 1 : COPY ./build.sh /src/build.sh
Step 1 : COPY ./modules.go /src/modules.go
Step 1 : RUN cd /src && ./build.sh "$(cat VERSION)-custom"
 ---> Running in c4374bf327f6
fetch http://alpine.gliderlabs.com/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://alpine.gliderlabs.com/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
(1/18) Installing openssl (1.0.2h-r1)
(2/18) Installing ca-certificates (20160104-r2)
(3/18) Installing libssh2 (1.6.0-r1)
(4/18) Installing curl (7.49.1-r1)
(5/18) Installing expat (2.1.1-r1)
(6/18) Installing pcre (8.38-r1)
(7/18) Installing git (2.6.6-r0)
(8/18) Installing go (1.5.4-r0)
(9/18) Installing libbz2 (1.0.6-r4)
(10/18) Installing libffi (3.2.1-r2)
(11/18) Installing gdbm (1.11-r1)
(12/18) Installing ncurses-terminfo-base (6.0-r6)
(13/18) Installing ncurses-terminfo (6.0-r6)
(14/18) Installing ncurses-libs (6.0-r6)
(15/18) Installing readline (6.3.008-r4)
(16/18) Installing sqlite-libs (3.9.2-r0)
(17/18) Installing python (2.7.12-r0)
(18/18) Installing mercurial (3.7.3-r1)
Executing busybox-1.24.2-r0.trigger
Executing ca-certificates-20160104-r2.trigger
OK: 250 MiB in 29 packages
# github.com/opencontainers/runc/libcontainer/system
exec: "gcc": executable file not found in $PATH
The command '/bin/sh -c cd /src && ./build.sh "$(cat VERSION)-custom"' returned a non-zero code: 2
```

**Comment by random0000** [comment]
Same issue as well

**Comment by josegonzalez** [comment]
Can you paste your custom dockerfile here?

**Comment by random0000** [comment]
So I just now did a "git clone https://github.com/gliderlabs/logspout.git" and then ran "docker build ." and received the above error.

**Comment by jmreicha** [comment]
Dockerfile:

```
FROM gliderlabs/logspout:master
ENV SYSLOG_FORMAT rfc3164
```

modules.go

```
package main

import (
	_ "github.com/gliderlabs/logspout/adapters/raw"
	_ "github.com/gliderlabs/logspout/adapters/syslog"
	_ "github.com/gliderlabs/logspout/httpstream"
	_ "github.com/gliderlabs/logspout/routesapi"
	_ "github.com/gliderlabs/logspout/transports/tcp"
	_ "github.com/gliderlabs/logspout/transports/udp"
	_ "github.com/looplab/logspout-logstash"
	_ "github.com/gliderlabs/logspout/transports/tls"
)
```

**Comment by jmreicha** [comment]
I add added gcc to the list of packages being installed in `build.sh`

```
apk add --update gcc go git mercurial
```

Now I'm getting the following error:

```
docker build -t logspout-test .                                                                                                                        jmreicha@aboutmes-MacBook-Pro
Sending build context to Docker daemon 4.096 kB
Step 1 : FROM gliderlabs/logspout:master
# Executing 3 build triggers...
Step 1 : COPY ./build.sh /src/build.sh
Step 1 : COPY ./modules.go /src/modules.go
Step 1 : RUN cd /src && ./build.sh "$(cat VERSION)-custom"
 ---> Running in 88a119960379
fetch http://alpine.gliderlabs.com/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://alpine.gliderlabs.com/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
(1/31) Installing binutils-libs (2.25.1-r0)
(2/31) Installing binutils (2.25.1-r0)
(3/31) Installing gmp (6.1.0-r0)
(4/31) Installing isl (0.14.1-r0)
(5/31) Installing libgomp (5.3.0-r0)
(6/31) Installing libatomic (5.3.0-r0)
(7/31) Installing libgcc (5.3.0-r0)
(8/31) Installing pkgconf (0.9.12-r0)
(9/31) Installing pkgconfig (0.25-r1)
(10/31) Installing mpfr3 (3.1.2-r0)
(11/31) Installing mpc1 (1.0.3-r0)
(12/31) Installing libstdc++ (5.3.0-r0)
(13/31) Installing gcc (5.3.0-r0)
(14/31) Installing openssl (1.0.2h-r1)
(15/31) Installing ca-certificates (20160104-r2)
(16/31) Installing libssh2 (1.6.0-r1)
(17/31) Installing curl (7.49.1-r1)
(18/31) Installing expat (2.1.1-r1)
(19/31) Installing pcre (8.38-r1)
(20/31) Installing git (2.6.6-r0)
(21/31) Installing go (1.5.4-r0)
(22/31) Installing libbz2 (1.0.6-r4)
(23/31) Installing libffi (3.2.1-r2)
(24/31) Installing gdbm (1.11-r1)
(25/31) Installing ncurses-terminfo-base (6.0-r6)
(26/31) Installing ncurses-terminfo (6.0-r6)
(27/31) Installing ncurses-libs (6.0-r6)
(28/31) Installing readline (6.3.008-r4)
(29/31) Installing sqlite-libs (3.9.2-r0)
(30/31) Installing python (2.7.12-r0)
(31/31) Installing mercurial (3.7.3-r1)
Executing busybox-1.24.2-r0.trigger
Executing ca-certificates-20160104-r2.trigger
OK: 324 MiB in 42 packages
# github.com/opencontainers/runc/libcontainer/system
../../opencontainers/runc/libcontainer/system/sysconfig.go:6:20: fatal error: unistd.h: No such file or directory
compilation terminated.
The command '/bin/sh -c cd /src && ./build.sh "$(cat VERSION)-custom"' returned a non-zero code: 2
```

**Comment by random0000** [comment]
I added:
apk add build-base gcc abuild binutils binutils-doc gcc-doc
to the build.sh file and it all seemed to work.  I'm sure this is overkill since it added a whole lot of items.

**Comment by josegonzalez** [comment]
I was able to see the same issue. I can only assume the underlying image changed?

**Comment by jmreicha** [comment]
I added `build-base` as a package and everything built okay but the image size is about 173mb which is probably not ideal.  I still have to test it out but at least it built!

**Comment by bn0ir** [comment]
@jmreicha, maybe you forgot to add «apt del build-base», I have 15.49 MB image size after image built

**Comment by hadri3n** [comment]
I have the same issue:

```
Building project logspout
Sending build context to Docker daemon 7.168 kB
Step 1 : FROM gliderlabs/logspout:latest
latest: Pulling from gliderlabs/logspout
7aabe7f6bcce: Already exists 
a5c9fdc2deaf: Already exists 
78d5d5a5a292: Already exists 
Digest: sha256:d608b3e72e4923a2e9e435ac4a2b79907e573b3839d7918521a15624a16b67d7
Status: Image is up to date for gliderlabs/logspout:latest
# Executing 2 build triggers...
Step 1 : COPY ./modules.go /src/modules.go
Step 1 : RUN cd /src && ./build.sh "$(cat VERSION)-custom"
 ---> Running in c050fd182213
fetch http://alpine.gliderlabs.com/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://alpine.gliderlabs.com/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
(1/18) Installing openssl (1.0.2h-r1)
(2/18) Installing ca-certificates (20160104-r2)
(3/18) Installing libssh2 (1.6.0-r1)
(4/18) Installing curl (7.49.1-r1)
(5/18) Installing expat (2.1.1-r1)
(6/18) Installing pcre (8.38-r1)
(7/18) Installing git (2.6.6-r0)
(8/18) Installing go (1.5.4-r0)
(9/18) Installing libbz2 (1.0.6-r4)
(10/18) Installing libffi (3.2.1-r2)
(11/18) Installing gdbm (1.11-r1)
(12/18) Installing ncurses-terminfo-base (6.0-r6)
(13/18) Installing ncurses-terminfo (6.0-r6)
(14/18) Installing ncurses-libs (6.0-r6)
(15/18) Installing readline (6.3.008-r4)
(16/18) Installing sqlite-libs (3.9.2-r0)
(17/18) Installing python (2.7.12-r0)
(18/18) Installing mercurial (3.7.3-r1)
Executing busybox-1.24.1-r7.trigger
Executing ca-certificates-20160104-r2.trigger
OK: 250 MiB in 29 packages
# github.com/opencontainers/runc/libcontainer/system
exec: "gcc": executable file not found in $PATH
The command '/bin/sh -c cd /src && ./build.sh "$(cat VERSION)-custom"' returned a non-zero code: 2
```

Dockerfile:
`FROM gliderlabs/logspout:latest`

modules.go:
```
package main

import (
  _ "github.com/gliderlabs/logspout/adapters/raw"
  _ "github.com/gliderlabs/logspout/httpstream"
  _ "github.com/gliderlabs/logspout/routesapi"
  _ "github.com/looplab/logspout-logstash"
  _ "github.com/gliderlabs/logspout/transports/udp"
  _ "github.com/gliderlabs/logspout/transports/tcp"
)
```

Docker version:
`Docker version 1.12.0, build 8eab29e`

and I run the following command:
`docker build --pull -t logspout .`

**Comment by josegonzalez** [comment]
Alright I can confirm this, please don't add a 👍 unless you have a fix for the problem.

**Comment by jmreicha** [comment]
@bn0ir D'oh you're right, I forgot to delete build-base.  After removing it, my image is down to 26mb, much better.

**Comment by josegonzalez** [comment]
Still much larger than the images we publish to docker.

**Comment by jmreicha** [comment]
I think the extra size might come from the additional entries I added to the `modules.go` file for logstash support.

**Comment by josegonzalez** [comment]
Official images are around 5mb.

**Comment by jmreicha** [comment]
@josegonzalez Confirmed that it doesn't work without `build-base`, which I think is adding the extra size.

**Comment by josegonzalez** [comment]
Yeah seems like gliderlabs/alpine dropped something critical here...

**Comment by Bekt** [comment]
#225 should fix this. However, I'm getting the following error with custom builds. Not sure if related or not.

```
⟩ docker build -t logspout-custom .
Sending build context to Docker daemon 4.608 kB
Step 1 : FROM gliderlabs/logspout:master
# Executing 3 build triggers...
Step 1 : COPY ./build.sh /src/build.sh
lstat build.sh: no such file or directory
```

```
⟩ cat Dockerfile
FROM gliderlabs/logspout:master
```

**Comment by josegonzalez** [comment]
Unrelated, thats a different issue. You'll need to copy a build.sh from our repo into the root of your directory.

**Comment by Bekt** [comment]
@josegonzalez thanks.

**Comment by indianscout** [comment]
Hola Amigos, this problem still exists with gliderlabs/logspout:v3.1:
```
Building logspout
Step 1 : FROM gliderlabs/logspout:v3.1
v3.1: Pulling from gliderlabs/logspout
Digest: sha256:028b5f6f49d87a10e0c03208156ffedcef6da2e7f59efa8886640ba15cbe0e69
Status: Downloaded newer image for gliderlabs/logspout:v3.1
# Executing 2 build triggers...
Step 1 : COPY ./modules.go /src/modules.go
Step 1 : RUN cd /src && ./build.sh "$(cat VERSION)-custom"
 ---> Running in e765f90032ad
fetch http://alpine.gliderlabs.com/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://alpine.gliderlabs.com/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
(1/18) Installing openssl (1.0.2h-r1)
(2/18) Installing ca-certificates (20160104-r2)
(3/18) Installing libssh2 (1.6.0-r1)
(4/18) Installing curl (7.49.1-r1)
(5/18) Installing expat (2.1.1-r1)
(6/18) Installing pcre (8.38-r1)
(7/18) Installing git (2.6.6-r0)
(8/18) Installing go (1.5.4-r0)
(9/18) Installing libbz2 (1.0.6-r4)
(10/18) Installing libffi (3.2.1-r2)
(11/18) Installing gdbm (1.11-r1)
(12/18) Installing ncurses-terminfo-base (6.0-r6)
(13/18) Installing ncurses-terminfo (6.0-r6)
(14/18) Installing ncurses-libs (6.0-r6)
(15/18) Installing readline (6.3.008-r4)
(16/18) Installing sqlite-libs (3.9.2-r0)
(17/18) Installing python (2.7.12-r0)
(18/18) Installing mercurial (3.7.3-r1)
Executing busybox-1.24.1-r7.trigger
Executing ca-certificates-20160104-r2.trigger
OK: 250 MiB in 29 packages
# github.com/opencontainers/runc/libcontainer/system
exec: "gcc": executable file not found in $PATH
Service 'logspout' failed to build: The command '/bin/sh -c cd /src && ./build.sh "$(cat VERSION)-custom"' returned a non-zero code: 2
Deployment failed!
29.08.2016 10:39:18 Deployment script ended.
```
I went through the posts above but there seems to be no solution - or is there...?

**Comment by josegonzalez** [comment]
3.1 will always have this issue. You'll want to build from master/latest.

**Comment by indianscout** [comment]
With the master I get this error:
```
Building logspout
Step 1 : FROM gliderlabs/logspout:master
master: Pulling from gliderlabs/logspout
Digest: sha256:465ebc1144d817a44bc6fc0ff1b7f1919cc82f65dae8603865015952504fba8c
Status: Downloaded newer image for gliderlabs/logspout:master
# Executing 3 build triggers...
Step 1 : COPY ./build.sh /src/build.sh
Service 'logspout' failed to build: lstat build.sh: no such file or directory
Deployment failed!
29.08.2016 10:34:05 Deployment script ended.
```

**Comment by indianscout** [comment]
BTW I prefer tags with fixed versions to avoid sudden problems when logspout:master gets updated. Probably a tag like v4.0 would be appropriate.

**Comment by josegonzalez** [comment]
You'll need to add the `build.sh` from this repo to your build directory or your builds will fail. That's basically what that error is about. I said the same thing to @Bekt above.

Regarding making a release, I'll look into it sometime this week. I too prefer released software, but life makes people busy with other stuff :)

**Comment by indianscout** [comment]
I'll wait with the quickfix on my side until there is a working image/tag. I very much appreciate your efforts :-) THX a lot!

**Comment by Bekt** [comment]
Some of you are trying to do a custom logspout-logstash build. I have put a working version of the image here: https://hub.docker.com/r/bekt/logspout-logstash/

**Comment by rsgross** [comment]
@josegonzalez I am building with the build.sh file in my build directory and I still receive the same error as above.
