### ISSUE TITLE
Can't evaluate fields in template strings

### ISSUE THREAD

**Issue by vivanov1410** [gliderlabs/logspout#273]
Gentlemen, I started to have issues with format templates after I upgraded docker engine from 1.12 to 1.13.

## Steps to reproducte
1. I run a docker service using following command
```
docker service create --name logspout \
  --network mejai-network \
  --mode global \
  --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
  --env SYSLOG_HOSTNAME='{{index .Config.Labels "com.docker.swarm.service.name"}}' \
  --env SYSLOG_TAG='{{.Name}}' \
  --env SYSLOG_STRUCTURED_DATA='cluster={{index .Config.Labels "ca.surrey.swarm.cluster"}}' \
  gliderlabs/logspout $ELK
```

## Actual result
```
Error response from daemon: rpc error: code = 3 desc = expanding env failed: expanding env "SYSLOG_HOSTNAME={{index .Config.Labels \"com.docker.swarm.service.name\"}}": template: expansion:1:15: executing "expansion" at <.Config.Labels>: can't evaluate field Config in type *template.Context
```

But if I run `docker inspect --format {{.ContainerName}} dda42680d044` it all works.

Any ideas?

**Comment by michaelshobbs** [comment]
Confirmed that this worked in docker 1.12. I fear this is a bit of chicken and egg where the labels aren't available in time. Not sure what we can reasonably do in logspout. Might be worth opening an issue against docker/docker?

docker 1.13 service inspect without env set:
```
            "Labels": {
                "com.docker.swarm.node.id": "10w0lr46p8q7d5mz2x97qxzkq",
                "com.docker.swarm.service.id": "llu4uvhaqw282edlq1a90c7he",
                "com.docker.swarm.service.name": "logspout",
                "com.docker.swarm.task": "",
                "com.docker.swarm.task.id": "dja3x17ac9e9v8xts27nmcgj8",
                "com.docker.swarm.task.name": "logspout.1.dja3x17ac9e9v8xts27nmcgj8"
            }
```

**Comment by mostolog** [comment]
I'm having a similar issue trying to set {{.Service.Name}}-{{.Task.Slot}} as syslog tag on my stack/compose file.
```
    logging:
      driver: 'syslog'
      options:
        tag: '{{.Service.Name}}-{{.Task.Slot}}'
        syslog-facility: 'local0'
```

suggestions?

**Comment by thiagonache** [comment]
I'm having this same issue, but when I have an env var in the compose file. Without env var, everything works.

**Comment by mostolog** [comment]
Seems this have been solved on docker 17.10

**Comment by thiagonache** [comment]
did you test it? i'm still having issues.
failed to update service prod-swarm_logspout: Error response from daemon: rpc error: code = InvalidArgument desc = expanding env failed: expanding env "SYSLOG_STRUCTURED_DATA=BLABLA@41058 tag=\"bla\" {{ index .Container.Config.Labels \"net.bla.app.tags\" }}\n": template: expansion:1:42: executing "expansion" at <.Container.Config.La...>: can't evaluate field Container in type *template.Context

**Comment by develar** [comment]
docker 17.10 cannot be used in production because contains some critical errors (that fixed in the 17.11, but again, it is edge release and another critical error maybe).

As a solution, I just fork this project and build own image. https://github.com/develar/logspout/commit/c9d3571cf596d3a0143ea2d8fc4abb2b50d0ba2b

**Comment by sandys** [comment]
is there an update for this ? can we use template variables in any environment variables ?

**Comment by streetster** [comment]
[context.go](https://github.com/docker/swarmkit/blob/master/template/context.go) looks to be the file that drives what can be templated. Could this be extended to support additional configuration (e.g. Node.Labels)?

**Comment by stiurin** [comment]
Problem is still there,
Tested on Docker 19.03.6
Used expression {{ index .Config.Labels "com.docker.swarm.service.name" }}

(ignore escape character this was run io ansible
Error response from daemon: rpc error: code = InvalidArgument desc = expanding env failed: expanding env \"RAW_FORMAT={{ index .Config.Labels \\\"com.docker.swarm.service.name\\\" }}\": template: expansion:1:16: executing \"expansion\" at <.Config.Labels>: can't evaluate field Config in type *template.Context\n"
